### ISSUE TITLE
Landfill Tool selective

### ISSUE THREAD

**Issue by Ranakastrasz** [christoph-frick/factorio-blueprint-tools#16]
The landfill tool doesn't appear to work as I would hope. Rather than only place landfill where it is needed, it appears to just place it under the entire blueprint. This means that nuclear setups, or powerlines, rail bridges, or so on don't really work as I would hope.

If this was intended, then I would instead request a toggle for this functionality.

I note that it would probably fail badly with modded entities.

**Comment by christoph-frick** [comment]
Thanks for your input. It was indeed intentional so far, as no one asked for it. Except for offshore pumps and curved rail this should be quite easy to do, since the selection boxes are known (which should cover most of the landfill locations).  Modded factorio is not supported right now anyway - so that is no problem. I'll look into that in the next days.

**Comment by Ranakastrasz** [comment]
Awesome. Can't wait XD.

**Comment by christoph-frick** [comment]
@Ranakastrasz I have implemented an "sparse" mode, that does not fill the whole area, but only the areas under the entities. The offshore-pump seems to work with that the way it is configured in factorio. Curved rails are not supported (they where not supported before). I'll create a new ticket for that.

Give it a try, if you find the time. If you find problems, please create new tickets and provide a minimal blueprint, that shows the problem.

**Comment by Ranakastrasz** [comment]
Tested it, looks like it works great, however, it doesn't include other tiles, like Brick or Concrete. Say If I want to make a city-grid, which in water sets up bridges in effect.
