### ISSUE TITLE
Image by blueprint

### ISSUE THREAD

**Issue by CanadianBeaver** [christoph-frick/factorio-blueprint-tools#29]
Can you add an image generator by blueprint, please?

**Comment by christoph-frick** [comment]
@CanadianBeaver Could you please be more specific? When loading a blueprint into one of the pages there is a SVG representation of the blueprint (outlines and random colors); do you want to be able to save this? Or do you mean a fully rendered preview, like in game? The later I will most likely not do, because it would need game assets (asking Wube for permission, ...)

**Comment by CanadianBeaver** [comment]
Okay, then can you make the `.svg` be opened in a new window or be saved? I am talking about the debug page.

**Comment by christoph-frick** [comment]
@CanadianBeaver The SVG is now shown inside an `img`-tag, so you can
right-click in your browser, and it will allow you to save/tab-open/...
etc it.

**Comment by CanadianBeaver** [comment]
Thank you
